### PR TITLE
Moved router to a separate folder for better code readability

### PR DESCRIPTION
**Pull request by tejasbenibagde**

### CODE REVIEW

**Review by 1ilit — CHANGES_REQUESTED** [review]
Hey! The theming is broken, can you check it out 

https://github.com/user-attachments/assets/9dd597e6-5b9f-461e-b27d-7528b30428b7

**Comment by tejasbenibagde** [comment]
ok I'm checking

**Comment by tejasbenibagde** [comment]
wait I tried to understand how you are manipulating the theme, and realized that you unnecessarily wrote too much code in many places just to switch into the light and dark theme and still it is not working, my question is that, if you are using tailwindcss then why did you not create a single separate hook to handle the dark and light mode state, one file(specifically a button) that helps you switch between dark and light theme, also you did not put the colors in the tailwindconfig for different themes, bro your life would have been thousand times easy if you have used the tailwindcss at it's full extent for this purpose. I would have helped you with this problem but I don't get too much time in a day, sorry bro

**Comment by dott1e** [comment]
Because I'm also using a UI library that handles theming differently. 70% of what you see in the app is all the UI library

**Comment by 1ilit** [comment]
@tejasbenibagde because I'm using a UI library that handles theming differently. I can't really control the theme of popovers with tailwind

**Comment by tejasbenibagde** [comment]
I'm not questioning your choices or the tools you're using; I just wanted to point out that it might have been easier to manage things like the dark/light toggle if Tailwind CSS had been used from the start for this purpose. It could have simplified the process by handling colors, fonts, themes, and more.

**Comment by tejasbenibagde** [comment]
That said, good luck with your project—it's a big one, and I’m sure it will turn out great!

**Comment by 1ilit** [comment]
Thanks man! I appreciate the contribution

**Pull request closed without merging**
