### PR TITLE
Fixed field circle icons not moving in Safari

### PR DESCRIPTION
**Pull request by ClaPalo**
Fix to #32. 
For some reason, the problem seems to be related to the opacity of the buttons. I fixed it by setting the opacity back to 1, which doesn't seem to ruin the UX.

### CODE REVIEW

**Comment by HaecheonLee** [comment]
The issue seems to be related with the style of transform set to `g` in `Canvas.jsx`. And the transform state is set by diagram. Personally, removing those style should not be relevant to the position of an element. We may need further investigation to solve it properly.

**Comment by ClaPalo** [comment]
It seems that by using RGBA for the colors, it's possible to set to opacity without creating the issue.

**Comment by HaecheonLee** [comment]
This seems to be the solution to fix it. I cannot find any other approach.

**Comment by HaecheonLee** [comment]
Fix seems to be required for Notes and subject area as well

**Review by 1ilit — APPROVED** [review]
Thank you!

**Pull request merged**
