### PR TITLE
Extended functionality of MSSQL to support NVARCHAR(MAX) and Nepali Language added

### PR DESCRIPTION
**Pull request by sudhirVoid**

### CODE REVIEW

**Comment by sudhirVoid** [comment]
Checked with the export functionality to ensure the right query is being generated . We are good with the query generated.

**Comment by sudhirVoid** [comment]
Added the functionality of Nepali language feature #309

**Review by 1ilit — CHANGES_REQUESTED** [review]
Please split these into 2 PRs

**Comment by sudhirVoid** [comment]
Two Prs are created :
https://github.com/drawdb-io/drawdb/pull/313
https://github.com/drawdb-io/drawdb/pull/312

**Pull request closed without merging**
