### PR TITLE
Docker Support

### PR DESCRIPTION
**Pull request by yash-chudasama**
**This Pull Request makes the following changes**
* Fixes issue 
   #11 

**Changes**
- Added Dockerfile
- Updated documentation in README.md file

### CODE REVIEW

**Comment by yash-chudasama** [comment]
Fixes issue #11

**Comment by ToshY** [comment]
This only partially implements #11. Requested is to have a docker image, not just the Dockerfile so it can be build locally. It additionally requires a bit of CI action to automatically build and push it to a registry (e.g. Dockerhub or GCR) upon new tag or release, which probably has to be discussed with the maintainer.

**Comment by jonas-grgt** [comment]
@ToshY true but this is a great first step!

**Review by 1ilit — CHANGES_REQUESTED** [review]
Hey @yash-chudasama, thank you for the PR :)

I tried running the container and when the page gets reloaded or a new window is opened the nginx server throws a 404 error. Could you please look into it? Maybe check out [this thread](https://stackoverflow.com/questions/43555282/react-js-application-showing-404-not-found-in-nginx-server).

Also I would really appreciate if you could fix the comments not to include NextJS since it's a simple react app.

Thank you so much!

**Comment by PRITHIVEE** [comment]
@yash-chudasama 

Kindly add the below line as part of the NGINX step

`echo 'server { listen 80; server_name _; root /usr/share/nginx/html;  location / { try_files $uri /index.html; } }' > /etc/nginx/conf.d/default.conf`

this will ensure that all the routes will respond with index.html if the file were not found

**Comment by DenuxPlays** [comment]
I would love to have this image available via a registry.
If that's something you want to implement I could make the github workflow.

**Comment by yash-chudasama** [comment]
> RUN echo 'server { listen 80; server_name _; root /usr/share/nginx/html; location / { try_files $uri /index.html; } }' > /etc/nginx/conf.d/default.conf

I've updated the same.

**Review by gautamkrishnar — APPROVED** [review]

**Review by 1ilit — APPROVED** [review]
Thank you!

**Pull request merged**
